openapi: 3.0.0
info:
  title: STD24014
  description: This is a specification of STD24014
  version: 1.0.0
servers:
  - url: http://localhost:8000 
paths:
  /cars:
    get:
      summary: Get a list of cars
      responses:
        '200':
          description: A JSON array of car objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 
    post:
      summary: Add a new car
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 
      responses:
        '201':
          description: Car created successfully
          content:
            application/json:
              schema:
                $ref: 